### ISSUE TITLE
Enhancement: Use Go time.Duration type for leeway

### ISSUE THREAD

**Issue by mcandre** [okta/okta-jwt-verifier-golang#18]
Go provides a built-in data type for reliably modeling periods, `time.Duration`. Using this type in our signatures helps developers to disambiguate units of time, as seconds vs minutes vs ... can result in configuration mistakes.

https://golang.org/pkg/time/#Duration

**Comment by nbarbettini** [comment]
Thanks for the suggestion! Right now we're focused on getting out the 1.0 release of our Go management SDK, but I'll keep this on the roadmap.
