### ISSUE TITLE
Provide dedicated error types

### ISSUE THREAD

**Issue by mcandre** [okta/okta-jwt-verifier-golang#24]
As a developer, it is difficult to get my application to respond properly to the different kinds of error states for token verification, when all these error states are rolled into an ambiguous string formatted error type.

Can we get fixed error code values, so that downstream processes can more easily identify and respond to these different error states? For example, there's a big difference between an expired token and a corrupt token.

At the very least, can we declare special strings like

```go
"`the `Expiration` was not able to be validated."
```

as public constants, so that developers can lean on string prefix matching to distinguish these?

**Comment by bretterer** [comment]
After much discussion, we have come to the conclusion that we do not want to have a maintained list of error code values as suggested here.  All error messages are defined in the code and we do have tests to make sure that we do not update the message, so you can do a string comparison.

At this point, we will be keeping the errors as they are, but are open to suggestions and PR's that we will take a look at if you have an idea on how to handle this.
