### ISSUE TITLE
Skip header key length check

### ISSUE THREAD

**Issue by mcandre** [okta/okta-jwt-verifier-golang#28]
The header key length check can probably be skipped, since we check for the required keys individually anyway. Additionally, as the JWT specification evolve over time and adds or removes required keys, we no longer have to carefully maintain this sensitive number.

https://github.com/okta/okta-jwt-verifier-golang/blob/develop/jwtverifier.go#L271-L274

Over the course of many millions of daily verifications, this time adds up for some real savings.

**Comment by bretterer** [comment]
Closing as inactive. If you are still having issues here, please feel free to open a new ticket.
