### ISSUE TITLE
Allow Custom JMK Caches

### ISSUE THREAD

**Issue by cfilby** [okta/okta-jwt-verifier-golang#37]
Would the Okta team be open to putting the cache behind a configurable interface, similar to the Discovery and Adapter interfaces? 

Allowing the caching mechanism to be configurable opens up a few nice possibilities:

* Storing JMK keys in caching service for faster cross process validation
* Background Refreshes of the JMK Keys
* Adjustment to cache expiration times

If this is something the team is interested in, I could open a PR for this at some point.

**Comment by bretterer** [comment]
Hi @cfilby, sorry for the long delay in a response here.  We would be open to a PR for this, but at this time, it is not on our roadmap to handle.

I am going to close this conversation in a week if there is no more discussion, but yes, we would love to see a PR for this kind of implementation in the future.

**Comment by ankitmalikg2** [comment]
Hi @bretterer, I need this option so can I create a PR on this repo?
