### ISSUE TITLE
Skip nonce validation for ID tokens from refresh grants

### ISSUE THREAD

**Issue by Kimchelly** [okta/okta-jwt-verifier-golang#43]
Would it be possible to optionally skip nonce validation for ID tokens? When I received an ID token from a refresh grant, the response didn't include a nonce. [This discussion](https://bitbucket.org/openid/connect/issues/1025/ambiguity-with-how-nonce-is-handled-on) seems to suggest that the nonce doesn't have to be returned with ID tokens from refresh token grants.

**Comment by bretterer** [comment]
We added some logic to make sure `nonce` is an empty string if it is null.  So in your case, you can set `ClaimsToValidate["nonce"]` to `""` and it will basically bypass this check
