### ISSUE TITLE
Verifying an Expired Token is resulting in Library Panicking

### ISSUE THREAD

**Issue by bandikishores** [okta/okta-jwt-verifier-golang#46]
If we call `jwtVerifierSetup.New().VerifyAccessToken(jwtString)` by passing an Expired `jwtString`, it Panics the Go-Routine instead of returning Error.

This is the Panic Trace:
```
panic: interface conversion: interface {} is nil, not map[string]interface {} [recovered]
	panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 7 [running]:
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/okta/okta-jwt-verifier-golang.(*JwtVerifier).VerifyAccessToken(0xc0000f1e98, 0x144b76a, 0x340, 0x176a380, 0xc0000c8638, 0x12)
	/Users/bandi/go/pkg/mod/github.com/okta/okta-jwt-verifier-golang@v0.1.0/jwtverifier.go:84 +0xc05
skyflow.com/common/pkg/auth.(*OktaService).ValidateAccessToken(0xc000069f48, 0x143a8d3, 0x14, 0x14434e8, 0x27, 0x14381bc, 0xd, 0x144b76a, 0x340, 0x5e95bbdf, ...)
```

The Reason:

- Okta Internally uses lestrrat-go library for verifying Signature (`jws.VerifyWithJKU`), which internally had a [Bug](https://github.com/lestrrat-go/jwx/pull/145/files#diff-a2f64e0e132b73c39460789f39582634L372) (_that got fixed 6 days ago but not released_). In a certain case(_During Signature Verification_), when error occurs inside the library it won't be returned to the caller. So both err and returned object are nil/empty, causing the typecast to fail.

Fix:

1. We upgrade once the new version of `lestrrat-go` is available.
2. Perform a Safe casting instead of a blind cast to ensure type safety. So at least a Panic wouldn't be generated.

**Comment by bretterer** [comment]
The package we are using has been updated and this is no longer an issue
