### ISSUE TITLE
golang v1.12 support

### ISSUE THREAD

**Issue by eephillip** [okta/okta-jwt-verifier-golang#52]
This might be a "won't support", but wanted to bring it up.
The introduction of `dur.Milliseconds()` breaks package support for golang v1.12.x
https://github.com/okta/okta-jwt-verifier-golang/blob/b08e23b547772aa6f1e1d28dfd6a14236a7d79b1/jwtverifier.go#L78

```
dur.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
```

That feature was added in v1.13
https://github.com/golang/go/commit/aa193c0b9623acd7397c0799ffc9efe5845216b2#diff-f8c9c9b812eac67d506765a54a7ed7d2

**Comment by bretterer** [comment]
Hi @eephillip!  Yes, We are aware that `dur.Milliseconds` was added in 1.13. The decision was to support 1.13+ as those are the current versions that you can download from the main download page.  https://golang.org/dl/. 

Is there something that would prevent you or others from being able to update from <1.13.x to at least 1.13.x?

**Comment by bretterer** [comment]
So, I updated to using `int64(dur.Seconds())`. This allows for use in 1.12.

https://github.com/okta/okta-jwt-verifier-golang/pull/56

**Comment by eephillip** [comment]
Awesome, thanks! Yeah your right, golang only supports the two latest major releases so I need to get onto a supported golang version. 
But this helps.
