### ISSUE TITLE
How to solve token constrain

### ISSUE THREAD

**Issue by nxquang1994** [okta/okta-jwt-verifier-golang#67]
I use the library to validate token whose header like this: 

`{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "l3sQ-50cCH4xBVZLHTGwnSR7680"
}`

I received the error: **"token is not valid: the tokens header contains too many properties. Should only contain `alg` and `kid`"**

Is there any parameters to config verifier to solve this problem?

Thank you

**Comment by monde** [comment]
@nxquang1994 apologies for a slow reply. I'm not as familiar with the `okta-jwt-verifier-golang` library. However, the error message seems to indirectly indicate that the example token shouldn't have a `typ` attribute. Instead only `alg` and `kid` attributes.

Let me know what you think or if you've found a solution.

**Comment by euforic** [comment]
Getting the same problem with an okta token. I can put in PR to add the missing field if that is acceptable?

**Comment by monde** [comment]
> Getting the same problem with an okta token. I can put in PR to add the missing field if that is acceptable?

Please do @euforic . I can collaborate on a PR with you. Currently afk until my next work day.

**Comment by monde** [comment]
@euforic @nxquang1994 apologies for having this continue on, I'm new to this library and new-ish to Okta.

Are you all using this package to verify JWTs that did not originate from Okta? Both the [Access Token header](https://developer.okta.com/docs/reference/api/oidc/#access-token-header) and the [ID Token header](https://developer.okta.com/docs/reference/api/oidc/#id-token-header) will only ever have `alg` and `kid` claims present.

I'd like to know the origin of the JWT you are trying to validate. If it is from somewhere other than Okta then that will help me better understand the context. Perhaps there is potential of writing a generic JWT validator and including it with this library.

cc: @bretterer @bdemers

**Comment by euforic** [comment]
> Are you all using this package to verify JWTs that did not originate from Okta? Both the [Access Token header](https://developer.okta.com/docs/reference/api/oidc/#access-token-header) and the [ID Token header](https://developer.okta.com/docs/reference/api/oidc/#id-token-header) will only ever have `alg` and `kid` claims present.

I am using this to validate an Okta auth token that also contains `typ`

**Comment by monde** [comment]
> > Are you all using this package to verify JWTs that did not originate from Okta? Both the [Access Token header](https://developer.okta.com/docs/reference/api/oidc/#access-token-header) and the [ID Token header](https://developer.okta.com/docs/reference/api/oidc/#id-token-header) will only ever have `alg` and `kid` claims present.
> 
> I am using this to validate an Okta auth token that also contains `typ`

@euforic is there anything special about your org or your app where this is showing up? Is it a production org? A preview org? Special feature flags on app and/or org? Thanks!

**Comment by monde** [comment]
@euforic I was grepping in the Okta core code, is your JWT dealing with CrowdStrike related 2FA?

**Comment by monde** [comment]
ok, just confirmed internally that `typ` claim is used in Fastpass. I'll gather some more information and make a plan about the PR.

**Comment by monde** [comment]
I opened #69 back up and will address required changes there. Thanks for helping out @euforic @nxquang1994
