### ISSUE TITLE
error: failed to decode JWT: missing 'jwks_uri' from metadata

### ISSUE THREAD

**Issue by andrewwatson** [okta/okta-jwt-verifier-golang#70]
I'm decoding a JWT I'm getting back from Okta (oktapreview.com) and I keep running into this error.  I'm pretty much using the [example code](https://github.com/okta/samples-golang/blob/master/okta-hosted-login/main.go) verbatim, especially the `exchangeCode` and `verifyToken` methods.

Any ideas?

**Comment by aarongranick-okta** [comment]
The `jwks_uri` is returned from the `.well-known/openid-configuration` endpoint on your issuer. For example: https://aarongranick.oktapreview.com/.well-known/openid-configuration

Can you confirm that your issuer is well-formed and is returning a valid response for this URL?

**Comment by andrewwatson** [comment]
yeah, i checked it out and it's definitely in there

```"jwks_uri": "https://atg.oktapreview.com/oauth2/v1/keys",```

**Comment by andrewwatson** [comment]
so this might be part of the problem... it was me.  

Our Okta preview installation has some seemingly non-standard paths so I had added this `Issuer:           ev.oauthIssuerURL + "oauth2/default",` 

and that might be what's breaking it.  I didn't realize what it was doing with that path.


```func verifyToken(t string) (*verifier.Jwt, error) {
	tv := map[string]string{}
	tv["nonce"] = nonce
	tv["aud"] = ev.oauthClientID
	jv := verifier.JwtVerifier{
		Issuer:           ev.oauthIssuerURL + "oauth2/default",
		ClaimsToValidate: tv,
	}

	result, err := jv.New().VerifyIdToken(t)
	if err != nil {
		return nil, fmt.Errorf("%s", err)
	}

	if result != nil {
		return result, nil
	}

	return nil, fmt.Errorf("token could not be verified: %s", "")
}```

**Comment by andrewwatson** [comment]
i figured it out.  I had added `/oauth2` to my issuer URL because a lot of the paths in our okta instance had that , which then broke the request to get the `jwks_uri` unintentionally.  I got it working!  Thanks!
