### ISSUE TITLE
stdlib JSON Unmarshal never creates []string, only []interface{}

### ISSUE THREAD

**Issue by awrenn** [okta/okta-jwt-verifier-golang#72]
https://github.com/okta/okta-jwt-verifier-golang/blob/628a050bbc3f9214b673344dea5371f6e471176e/adaptors/lestrratGoJwx/lestrratGoJwx.go#L78

Based on this adapter, any JWT that has multiple `aud` claims (like Auth0 often issues - their JS SDKs always require the scope openid which causes their own `/userinfo` audience to be included in the `aud` field in addition to our resource server) will be converted by the json package into a field of type []interface{}, not []string.

https://github.com/okta/okta-jwt-verifier-golang/blob/628a050bbc3f9214b673344dea5371f6e471176e/jwtverifier.go#L215 
Here, the validateAudience function attempts to extract the `aud` claim from the token, but then would fail to recognize []interface{} as a valid type for `aud`.

Can this switch statement be expanded to handle []interface{} -> []string first, and then attempt to handle []string the same way as above?

**Comment by laura-rodriguez** [comment]
Hi @awrenn,

Thanks for your issue. Someone from team will review it soon.

cc @MikeMondragon-okta

**Comment by monde** [comment]
hi @awrenn okta/okta-jwt-verifier-golang is specifically for use with JWTs from Okta and not a general purpose JWT verifier. That said, I see your point about how easy it would be to add an addition type assertion for `[]interface{}` in the case statement for `validateAudience`. Can you give me a PR so we can work on this together?

**Comment by awrenn** [comment]
Yeah I read through most of it before attempting to use it with Auth0 tokens - our app allows both so I figured if I could keep it consistent that would be easiest :) Thanks for your help Mike.

Opening the PR now - I haven't signed a CLA yet but I can

**Comment by monde** [comment]
@awrenn upon review, I'd call this an obvious fix (small refactor / re-ordering of objects), I don't think you need to submit a CLA: https://developer.okta.com/cla/

"`If you believe your contribution is an Obvious Fix, please add “Obvious Fix” to the pull request description. `"

**Comment by monde** [comment]
clean up, we released this fix in v1.1.2
